public class Problem0002 {
    public static void main(String[] args){
        // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        System.out.println(fibUnderFourMil());
    }

    public static int fibUnderFourMil() {
        // if (val%3==0){
        //     return true;
        // }
        // return false;
        int x1 = 1, x2 = 1, y = 0, sum = 0;
        y = x1+x2;

        while (y <4000000) {
            if (y%2 == 0){
                sum += y;
            }
            x1 = x2;
            x2 = y;
            y = x1+x2;
        } 
        return sum;
    }

}